### ISSUE TITLE
some issues for Xcode10 beta

### ISSUE THREAD

**Issue by keeprice-app** [XVimProject/XVim2#153]
Hi,  I compiled XVIM2 with xcode10 beta, and re-signed the Xcode beta just as the install instruction of xvim2. It can be launched with Xcode beta. What a great work guys!

However, I found some bugs like:
1. if I use command 'o' to add a new line, it bings the latest char to the new line.
2. "yyp" will paste the copied line just at the cursor position.
It looks like some glitch with newline related function.

I would try to fix it. however I have no any related experiences about this project.
It would be great if anyone can point some direction, or if someone can fix it would be awesome.  f^^

Thank you very much.

**Comment by wang9262** [comment]
The same issue here. And the cursor is the same as the insert mode when using visual or normal mode. The image is shown as below.

![](https://user-images.githubusercontent.com/5634225/41019111-d88a0eb0-698f-11e8-9f33-cf9ae3de56a1.png)

**FYI**: In my situation,I should use `sudo make` to generate the plugin, or  it would fail to build the commad if just using `make` command described in README.

**Comment by sobri909** [comment]
I'm getting a weird issue where the plugin isn't copied to the correct folder because the home path isn't being expanded correctly. `~Library/Application Support/...` is being expanded to `/~/Library/Application Support/...`, ie a tilde directory off the root dir! Not a great place to put things 😉

My workaround for this is to open the project in Xcode and change the path in the "Copy Files" section of "Build Phases" to be an absolute path, ie `/Users/matt/Library/...` instead of `~/Library/...`. 

That solves that problem, and allows the plugin to both build and install correctly. But I'm still not yet able to get it to load in Xcode 10. It asked me if I wanted to load it, so it definitely saw it. But then seemingly rejected it anyway. But there's no mention of it in the `defaults` for Xcode 10. Hmm.

So I'm still investigating. (It's not a matter of resigning, which I know is everyone's first guess. That's the first thing I did after installing the beta! But I'm going to do it again now anyway, for superstition's sake).

**Comment by sobri909** [comment]
And now after building with the latest develop branch Xcode 10 is accepting the plugin, and it's working properly. (Albeit with the above described cursor problem). Weird 😳

Apple really don't want to make this easy for us eh. You'd think Vim style editing would be a high priority prestige feature for them. But instead we're forced over into a ghetto of illegitimate plugins. Sigh.

**Comment by zconnelly** [comment]
After going through this thread and following the instructions as closely as I can -- I still can't get it to work.

`make` will run just fine -- and I'll get the confirmation dialogue to load the plugin -- but then when I launch it afterward the plugin doesn't seem to be loaded.

I tried running `defaults delete com.apple.dt.Xcode...` as mentioned in the `README` (which will allow me to try to load the extension again, but this, too, doesn't work)

I'm running 10.14 Mojave, though, so I'm sure that has something to do with it. (For what it's worth, even on Mojave, XVim2 still works on XCode 9.4)

Happy to help debug if someone could give me a touch of guidance!

**Comment by ccwasden** [comment]
Didn't work on my first try, but after killing simulator, restarting my computer and running make again, Xcode took to the plugin when I opened it. But the issues with the lack of a block cursor are rough... in insert mode I can't get the cursor to the very end of the line no matter what I do, and `o` carries down the last character like @keeprice-app mentioned

**Comment by hawflakes** [comment]
Noticed that I can't see the lldb prompt because it's also applied to that view. Is it possible to disable it for that?

**Comment by JadianZheng** [comment]
I think this issue can be close. See @ #155, @keeprice-app

**Comment by keeprice-app** [comment]
great! thanks a lot!

**Comment by Paulche** [comment]
Thanks!

**Comment by mgerb** [comment]
I had permission issues issues while running `make` on Xcode 10. The following solution worked for me.

```
sudo chown -R username /~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins
```
