### ISSUE TITLE
It doesn't work,Help!!!

### ISSUE THREAD

**Issue by crazyherozk** [XVimProject/XVim2#3]
I use make to build the project and got build succeeded, but the plugin hasn't loaded in Xcode 9.

**Comment by shanecb** [comment]
Make sure that you code sign Xcode like it says here https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md

**Comment by basketwang** [comment]
It's not working on my side too. I can see the reminder to launch the bundle, but nothing happens inside xcode

**Comment by basketwang** [comment]
@shanecb Does it work for you?

**Comment by shanecb** [comment]
@basketwang Yes, the plugin is working for me, but I haven't tried it in the App Store version of Xcode 9, only in Xcode 9 beta. One thing to note is that this version of Xvim is by no means complete as I think @JugglerShu was just posting his code so we can get an idea of the direction he's trying to go with this, so in this version, the cursor's appearance does not differ when you switch to normal mode, and the movements are very limited at the moment (h, j, k, l, b, w, etc.). So maybe it is working for you and you didn't notice since the cursor didn't look different? I'll try it in the App Store version of Xcode 9 and let you know what happens

**Comment by shanecb** [comment]
Okay, I tried it with the release version of Xcode 9 and it didn't work for me at first either. It looks like it's because the UUID for Xcode 9 isn't in the Info.plist, but that's fixed [here](https://github.com/mingming1222/XVim2) and I think in a couple of the other forks. But the fork I linked has also implemented the cursor change when in normal mode, so that's kind of nice

**Comment by basketwang** [comment]
@shanecb Thanks so much. I tried that one. it can be loaded to xcode and I can see the changed cursor. But xcode crashes every time when I press a key. I guess it's still not stable yet. Thanks anyway.

**Comment by FongRay** [comment]
@shanecb Thanks, load success, but not work well. For example, the `Shift + $`, `gg` not work.

**Comment by antmd** [comment]
Please try with the latest version, being sure to first remove any old version of the plugin from your Xcode plugins directory.

**Comment by antmd** [comment]
Closing  -- please reopen if it still doesn't work for you.

**Comment by yukitoto** [comment]
I use master and Xcode9.0. It does not work too.
